### ISSUE TITLE
Solr "No such core" error, causing velocity NPE

### ISSUE THREAD

**Issue by buske** [phenotips/phenomecentral.org#46]
Just tried to build latest PC and it is unable to load any part of the ontology. Seems like a solr issue.

Getting the following error in the server logs:
```
2014-12-15 17:56:03,472 [http://localhost:8080/bin/P0000001] ERROR p.o.i.s.HumanPhenotypeOntology - Failed to search: No such core: hpo 
org.apache.solr.common.SolrException: No such core: hpo
```
and
```
2014-12-15 17:55:59,955 [http://localhost:8080/bin/P0000001] ERROR .i.s.MendelianInheritanceInMan - Failed to count ontology terms: No such core: omim 
org.apache.solr.common.SolrException: No such core: omim
```

resulting in the following on the client side:

```
Caused by: org.xwiki.velocity.XWikiVelocityException: Failed to evaluate content with id [xwiki:data.P0000001]
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:247)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:187)
	at org.xwiki.rendering.internal.macro.velocity.VelocityMacro.evaluateString(VelocityMacro.java:124)
	... 185 more
Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'display' in  class org.phenotips.tools.PhenotypeDisplayTools threw exception java.lang.NullPointerException at xwiki:data.P0000001[line 32, column 44]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:228)
	... 187 more
Caused by: java.lang.NullPointerException
	at org.phenotips.ontology.internal.solr.AbstractSolrOntologyService.search(AbstractSolrOntologyService.java:145)
	at org.phenotips.ontology.internal.solr.AbstractSolrOntologyService.search(AbstractSolrOntologyService.java:138)
	at org.phenotips.tools.PropertyDisplayer.replaceOtherWithTopSections(PropertyDisplayer.java:167)
	at org.phenotips.tools.PropertyDisplayer.<init>(PropertyDisplayer.java:97)
	at org.phenotips.tools.PhenotypeDisplayTools.display(PhenotypeDisplayTools.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
	... 193 more
```

**Comment by sdumitriu** [comment]
Doesn't happen anymore, might have been caused by phenotips/patient-network#51

**Comment by sdumitriu** [comment]
Still happens...

**Comment by sdumitriu** [comment]
Was a POM issue in phenotips, see phenotips/phenotips@292329a5341260dbdaf6b1e8d6fc562bba78a70e, which cause incompatible versions of Lucene and Solr to be used in the package. Building a stable version didn't have the issue.
